
GLM_HDR=../../../third_party/glm-master/

#SRC= vectors/1_vector.cpp
#SRC= vectors/2_unit_vector.cpp
#SRC= vectors/3_dot_product.cpp
#SRC= vectors/4_cross_product.cpp
#SRC= 2_matrix/point_in_3d.cpp
#SRC= 2_matrix/3_rotate.cpp
SRC= 2_matrix/5_multipe_transformations.cpp

all:
	g++ -std=c++20 $(SRC) -o prog -I$(GLM_HDR)

clean:
	rm -f prog